vs_mvc5_db_mssql_emploee_datatable/Controllers/AppController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace vs_mvc5_db_mssql_emploee_datatable.Controllers
{
    public class AppController : Controller
    {
        // GET: App
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult loaddata()
        {
            using (AppContextEntities dc = new AppContextEntities())
            {
                dc.Configuration.LazyLoadingEnabled = false; // if your table is relational, contain foreign key
                var data = dc.Emploees.OrderBy(a => a.EmploeeId).ToList();
                return Json(new { data = data }, JsonRequestBehavior.AllowGet);
            }
        }
    }
}

vs_mvc5_db_mssql_emploee_datatable/Views/App/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>
<div style="width:90%; margin:0 auto">
    <table id="myTable">
        <thead>
        <tr>
            <th>Фамилия</th>
            <th>Имя</th>
            <th>Отчество</th>
            <th>Должность</th>
        </tr>
        </thead>
    </table>
</div>

@* Load datatable css *@
<link href="~/Content/DataTables/css/jquery.dataTables.min.css" rel="stylesheet" />
@* Load datatable js *@
@section Scripts{
<script src="~/Scripts/DataTables/jquery.dataTables.min.js"></script>
<script>
    $(document).ready(function () {
        $('#myTable').DataTable({
            "ajax": {
                "url": "/app/loaddata",
                "type": "GET",
                "datatype": "json"
            },
            "columns" : [
                { "data": "LastName", "autoWidth": true },
                { "data": "FirstName", "autoWidth": true },
                { "data": "MiddleName", "autoWidth": true },
                { "data": "PositionId", "autoWidth": true }
            ]
        });
    });
</script>
}

vs_mvc5_db_mssql_emploee_datatable/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title – приложение ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Имя приложения", "Index", "App", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Домашняя страница", "Index", "App")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year – приложение ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>